### ISSUE TITLE
Virtual keyboard functionality and customization

### ISSUE THREAD

**Issue by kosmosnautti** [Salamek/chromium-kiosk#98]
So far this project has worked wonderfully, but I've come across a small problem regarding the virtual keyboard when using this with a touch screen.

I have a website using basically the whole size of the web view window. I also have input fields on different parts of the screen, and the problem is that whenever I click on a field that's on the lower part of the screen, the virtual keyboard pops up (as expected) and blocks the view to the actual input field of the website, so the problem is that I cannot see what I'm typing into the field.

I was thinking if it would be possible to add an option to for example resize the web view window when the virtual keyboard is opened (so that the web view window would be resized to start from the top of the screen and end at the top of the virtual keyboard), and then possibly scroll (if needed/possible) the web view window to the clicked input field, so that the field would be visible while typing? That's just the first solution that came to my mind, perhaps there are more elegant ones.

And last but not least, not an issue per se but more of a feature request: Would it be possible to also add some customization options for the virtual keyboard? What I'd like to see for example:
- Adjustment of the size of the keyboard (mainly to make it a little smaller)
- Definition of the starting layout/locale of the keyboard (or does this come from the OS settings?)

**Comment by Salamek** [comment]
Well this will needs some R&D, there are like 3 ways how to do/fix this, none of them easy to implement:
1. Keep using QWidgets, listen for virtual keyboard events and offset PageView up (+vkb height) without changing its w/h (to not change page layout, responsive css exists) and scroll to focused input, revert that when vkb is closed. 
2. Rewrite qiosk to use QML, then embed the QML vkb into qiosk, that allows to override bunch of things etc but i don't want to really do that
3. Render floating input on top of vkb to display what is written

I think i will go with 1 for now...
Also qvirutalkeyboard uses system settings for input locale

**Comment by ArnaudDeClerck** [comment]
Hi,
This is a feedback that we get a lot also.
One on my idea would be to add the feedback of what you typ at the top of the keyboard.
i have saw that in a lot of different system.
I don't know if this is feasible and how much work it would take to do it. 
This can also maybe be under a configuration is some people doesn't need it. 
Regards and thx for the nice job.

**Comment by Salamek** [comment]
Should be fixed in latest release of qiosk.

**Comment by ArnaudDeClerck** [comment]
Hi Adam, 

Thanks for the update. For me it a good step but still not solve all possible use case. Popups don't play well with the resizing (But that is something i can maybe solve in my application.
I tested a same solution from Siemens based on debian also. And the keyboard was floating and moving away from where the touch was detected.
I don't know how difficult it's to implement that but that would solve all use cases i think.

The current fix is already something useful. Is there a possibility to disabled that feature within the configuration ?

Regards

**Comment by Salamek** [comment]
@ArnaudDeClerck 
Hi,

Thanks for the feedback.

Could you share a link to the Siemens software you tested, or perhaps a video/screen recording showing the behavior? I'd like to better understand what implementation you're referring to and how the keyboard behaves when it appears.

When you mention that the keyboard was floating and moving away from where the touch was detected, do you mean a floating virtual keyboard that is repositioned near the focused input instead of resizing the viewport?

Also, when you ask about disabling the feature in the configuration, are you referring to the viewport resizing/scrolling behavior introduced by this fix?

Thanks,
Adam

**Comment by ArnaudDeClerck** [comment]
@Salamek 
Hi,
Here is the link to the siemens software. https://support.industry.siemens.com/cs/document/109998055/industrial-web-panel-advanced-v1-2?dti=0&lc=en-BE 
Unfortunately we can only get that software when buying a specific hardware and not as standalone installer.
I don't have that hardware in testing and i don't have any video or prontscreen.

Yes the keyboard was always moving near the focused input. when the viewport stays always at the same size.

Yes i was talking about the fix implemented in the new version.

Regards

Arnaud

**Comment by Salamek** [comment]
> Yes the keyboard was always moving near the focused input. when the viewport stays always at the same size.

Well that means the keyboard needs to be small no?

> Yes i was talking about the fix implemented in the new version.

No it is replacement of original keyboard implementation, configuration option to disable it could be introduced, BUT i'm planning to migrate to Wayland anyway and old keyboard approach does not work in Wayland at all.

I could add configuration option to control viewport resizing (enable/disable)? That would basically bring back old functionality?

**Comment by ArnaudDeClerck** [comment]
@Salamek

> Well that means the keyboard needs to be small no?

No the keyboard was always the same size and was taking the full width. if it could not be placed at the bottom without being in front of the input field, it was above it. The height of it was +- 30% of the weight of the viewport.

> I could add configuration option to control viewport resizing (enable/disable)? That would basically bring back old functionality?

I think that's not a bad idea, but it's just a personal point of view.

Regards

**Comment by ArnaudDeClerck** [comment]
Hi @Salamek,

Did you have any time to take a look at this proposition ?

Regards
Arnaud

**Comment by Salamek** [comment]
@ArnaudDeClerck yes, i had to first address issues and todos i had :-) I agree that this virtual keyboard behavior is ok, but i want to make it configurable so qiosk users can pick what they like to use + i want to expose some qtvirtualkeyboard configuration options... that will require some refactoring to be done and it will take a while.
